### ISSUE TITLE
License details are lacking

### ISSUE THREAD

**Issue by nicorikken** [dpinney/gridlabSublime#1]
I'm interested in forking this project for inclusion in the Atom editor, but I'm able to as no free license has been provided. I was hoping you could choose a free license for your project to enable me to reuse your work. In this case I'd opt for the [MIT license](https://github.com/atom/atom/blob/master/LICENSE.md), as is used for the Atom editor, and enables inclusion in projects of various licenses. [Wikipedia](https://en.wikipedia.org/wiki/MIT_License)

**Comment by nicorikken** [comment]
@dpinney I haven't head from you up until now. I find that unfortunate. I'm still interested in reusing your work. Recently I have been working improvements on the https://github.com/asciidoctor/atom-language-asciidoc project to get going with language parsing. I feel I can start working on a Gridlab language support very soon, so I'm still hoping you can attach a free license on the project, allowing reuse.

**Comment by dpinney** [comment]
Hi Nico. Sorry I missed your previous message - I wasn't watching the repo. I licensed the code under the MIT license just now. I hope it is useful to you in your project.

**Comment by nicorikken** [comment]
@dpinney Thanks. I had such a suspicion already, that's why I added another comment. Don't be sorry. I'll probably have a go at it very soon. It will be a preliminary step for me to get going with Gridlab-D. Looking at the glm-files without syntax-highlighting isn't ideal.
For now I still have issues getting Gridlab-D to even run, let alone being in the position to play with it. If you have some getting-started resources to refer to, I'd be glad to receive them. It is quite a large and complicate project to grasp, but also very interesting and promising.

**Comment by dpinney** [comment]
GridLAB-D is powerful. I've been working with it for the past couple years, and I've developed [a GUI for it](https://github.com/dpinney/omf/), so let me know if you'd be interested in chatting about it.

**Comment by nicorikken** [comment]
Certainly I'd be willing to talk about it. I got the sense that OMF had a scope wider than Gridlab-D. I also looked into GridSpice, although that project seems to be dead unfortunately.

**Comment by dpinney** [comment]
Yeah, we try to do a lot more. Our GridLab content is concentrated in this section of the code: https://github.com/dpinney/omf/wiki/Models-~-gridlabMulti
